---
title: "Comparison to pmsampsize"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{pmsampsize}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tidyverse)
library(pmsims)
library(pmsampsize)
library(furrr)
plan(multisession, workers = 20)
set.seed(42)
```

```{r}
opts <- expand_grid(expected_c = seq(0.6, 0.9, 0.1),
                    prevalence = c(0.1, 0.5),
                    n_parameters = c(10, 50, 100))

opts$pmsampsize <-
  future_pmap(
    opts,
    \(expected_c, prevalence, n_parameters) {
      pmsampsize(
        type = "b",
        parameters = n_parameters,
        prevalence = prevalence,
        cstatistic = expected_c,
        seed = 42
      )
    },
    .options = furrr_options(seed = 42))


opts$pmsampsize <- opts$pmsampsize |>
  map(\(r) { 
    x <- r$results_table[1:3, 1]
    names(x) <- paste0("criteria", 1:3)
    return(x)
    })

opts |>
  unnest_wider(pmsampsize)

```

```{r}
opts$pmsims <- 
  future_pmap(
    opts,
    \(expected_c, prevalence, n_parameters, ...) {
      print(c(expected_c, prevalence, n_parameters))
      r <- try(simulate_binary(signal_parameters = n_parameters,
                      baseline_prob = prevalence,
                      large_sample_performance = expected_c,
                      min_sample_size = 100,
                      max_sample_size = 10000)
      )
      if (class(r) == "try-error") {
        return(NA)
      } else {
        return(list(mlpwr = r$min_n,
                    crude = r$min_n_crude))
      }
    },
    .options = furrr_options(seed = 42)
  )
```

```{r}
opts <- opts |>
  unnest_wider(pmsims)

print(opts, n = 100)
```

```{r}
opts |>
  pivot_longer(pmsampsize:pmsims) |>
  ggplot() +
  aes(x = n_parameters,
      y = value,
      color = name) +
  geom_point() +
  geom_line() +
  facet_grid(cols = vars(paste("expected_c:", expected_c)),
             rows = vars(paste("prevalence:", prevalence)))


```